import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { TransformControls } from 'three/addons/controls/TransformControls.js';
import { catalog, createCatalogObject } from './object-library.js';

const VERSION='0.4.0';
const HUMAN_HEIGHT=1.75;
const $=s=>document.querySelector(s);
const planCanvas=$('#planCanvas'),ctx=planCanvas.getContext('2d'),viewport=$('#threeViewport');
const ui={
  wallTool:$('#wallToolBtn'),rectTool:$('#rectToolBtn'),selectTool:$('#selectToolBtn'),defaultHeight:$('#defaultHeight'),wallThickness:$('#wallThickness'),gridSize:$('#gridSize'),angleSnap:$('#angleSnap'),
  emptyInspector:$('#emptyInspector'),wallInspector:$('#wallInspector'),objectInspector:$('#objectInspector'),surfaceInspector:$('#surfaceInspector'),wallNumber:$('#wallNumber'),wallLength:$('#wallLength'),selectedHeight:$('#selectedHeight'),selectedThickness:$('#selectedThickness'),deleteWall:$('#deleteWallBtn'),
  wallCount:$('#wallCount'),objectCount:$('#objectCount'),surfaceCount:$('#surfaceCount'),planStatus:$('#planStatus'),demo:$('#demoBtn'),hotelDemo:$('#hotelDemoBtn'),newPlan:$('#newPlanBtn'),library:$('#objectLibrary'),search:$('#objectSearch'),refresh:$('#refreshObjectsBtn'),
  objectTitle:$('#objectTitle'),objX:$('#objX'),objY:$('#objY'),objZ:$('#objZ'),objRX:$('#objRX'),objRY:$('#objRY'),objRZ:$('#objRZ'),objW:$('#objW'),objH:$('#objH'),objD:$('#objD'),deleteObject:$('#deleteObjectBtn'),
  floorMaterial:$('#floorMaterial'),ceilingMaterial:$('#ceilingMaterial'),showCeiling:$('#showCeiling'),ceilingHeight:$('#ceilingHeight'),customTexture:$('#customTexture'),deleteSurface:$('#deleteSurfaceBtn'),gizmoToggle:$('#gizmoToggle'),transformHint:$('#transformHint'),version:$('#versionBadge')
};
ui.version.textContent=`v${VERSION}`;

const state={walls:[],objects:[],surfaces:[],selected:null,tool:'wall',drawingPoints:[],rectStart:null,hoverWorld:null,grid:.25,defaultHeight:2.6,defaultThickness:.15,pan:{x:0,y:0},zoom:70,isPanning:false,lastMouse:null,gizmoEnabled:false,transformMode:'translate',transformSession:null,lastPointer:{x:innerWidth/2,y:innerHeight/2}};

// ---------- materials ----------
const materialDefs={
  concrete:{name:'Hormigón',color:0x777b80},wood:{name:'Madera',color:0x8b6847},tile:{name:'Baldosa clara',color:0xc9c7bd},checker:{name:'Damero',color:0xbdbdb7},carpet:{name:'Alfombra',color:0x665d5b},dark:{name:'Oscuro',color:0x34383d},white:{name:'Blanco',color:0xe3e1d8}
};
for(const [k,v] of Object.entries(materialDefs)){ui.floorMaterial.add(new Option(v.name,k));ui.ceilingMaterial.add(new Option(v.name,k));}
ui.floorMaterial.value='wood';ui.ceilingMaterial.value='white';
const texCache=new Map();
function proceduralTexture(key){if(texCache.has(key))return texCache.get(key);const c=document.createElement('canvas');c.width=c.height=128;const g=c.getContext('2d');
  if(key==='wood'){g.fillStyle='#866445';g.fillRect(0,0,128,128);g.strokeStyle='#5e452f';g.lineWidth=2;for(let y=8;y<128;y+=16){g.beginPath();g.moveTo(0,y);g.bezierCurveTo(30,y-5,80,y+6,128,y);g.stroke();}for(let x=0;x<128;x+=32){g.strokeStyle='#745437';g.strokeRect(x,0,31,128);}}
  else if(key==='tile'){g.fillStyle='#cbc8bd';g.fillRect(0,0,128,128);g.strokeStyle='#777';g.lineWidth=2;for(let x=0;x<=128;x+=32){g.beginPath();g.moveTo(x,0);g.lineTo(x,128);g.stroke()}for(let y=0;y<=128;y+=32){g.beginPath();g.moveTo(0,y);g.lineTo(128,y);g.stroke()}}
  else if(key==='checker'){for(let y=0;y<4;y++)for(let x=0;x<4;x++){g.fillStyle=(x+y)%2?'#36383a':'#d4d1c8';g.fillRect(x*32,y*32,32,32)}}
  else if(key==='carpet'){g.fillStyle='#655b59';g.fillRect(0,0,128,128);for(let i=0;i<900;i++){const a=Math.random()*.22+.04;g.fillStyle=`rgba(255,255,255,${a})`;g.fillRect(Math.random()*128,Math.random()*128,1,1)}}
  else {g.fillStyle='#888';g.fillRect(0,0,128,128)}
  const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(3,3);t.colorSpace=THREE.SRGBColorSpace;texCache.set(key,t);return t;
}
function makeSurfaceMaterial(key,customData=null){const def=materialDefs[key]||materialDefs.concrete;const opts={color:def.color,roughness:.82,side:THREE.DoubleSide};if(['wood','tile','checker','carpet'].includes(key))opts.map=proceduralTexture(key);if(key==='custom'&&customData){if(!texCache.has(customData)){const t=new THREE.TextureLoader().load(customData);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(3,3);t.colorSpace=THREE.SRGBColorSpace;texCache.set(customData,t)}opts.map=texCache.get(customData);opts.color=0xffffff;}return new THREE.MeshStandardMaterial(opts)}

// ---------- THREE ----------
const scene=new THREE.Scene();scene.background=new THREE.Color(0x10151b);scene.fog=new THREE.Fog(0x10151b,28,70);
const camera=new THREE.PerspectiveCamera(48,1,.05,150);camera.position.set(9,8,11);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;viewport.appendChild(renderer.domElement);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,1.1,0);orbit.enableDamping=true;orbit.maxPolarAngle=Math.PI*.49;orbit.minDistance=2;orbit.maxDistance=60;
scene.add(new THREE.HemisphereLight(0xcfe3ff,0x34312d,1.5));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(8,12,7);sun.castShadow=true;scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(60,60),new THREE.MeshStandardMaterial({color:0x232930,roughness:.98}));ground.rotation.x=-Math.PI/2;ground.position.y=-.02;ground.receiveShadow=true;scene.add(ground);scene.add(new THREE.GridHelper(60,240,0x495361,0x303842));
const wallGroup=new THREE.Group(),objectGroup=new THREE.Group(),surfaceGroup=new THREE.Group(),helperGroup=new THREE.Group();scene.add(surfaceGroup,wallGroup,objectGroup,helperGroup);
const renderedObjects=new Map();
function createHuman(){const g=new THREE.Group(),r=.22,bh=HUMAN_HEIGHT-r*2,m=new THREE.MeshStandardMaterial({color:0x68b6ff,roughness:.45});const body=new THREE.Mesh(new THREE.CylinderGeometry(r,r,bh,18),m);body.position.y=r+bh/2;const top=new THREE.Mesh(new THREE.SphereGeometry(r,18,12),m);top.position.y=r+bh;const bottom=new THREE.Mesh(new THREE.SphereGeometry(r,18,10),m);bottom.scale.y=.55;bottom.position.y=r*.55;g.add(body,top,bottom);g.position.set(-1.2,0,-1.1);return g}scene.add(createHuman());

const transform=new TransformControls(camera,renderer.domElement);const transformHelper=transform.getHelper();scene.add(transformHelper);transformHelper.visible=false;
transform.addEventListener('dragging-changed',e=>orbit.enabled=!e.value);
transform.addEventListener('objectChange',()=>{const g=transform.object;if(!g?.userData.objectId)return;const o=findObject(g.userData.objectId);if(!o)return;o.x=g.position.x;o.y=g.position.y;o.z=g.position.z;o.rx=g.rotation.x;o.ry=g.rotation.y;o.rz=g.rotation.z;syncObjectInspector(o);updateSelectionHelper(g)});
transform.addEventListener('mouseUp',()=>{const g=transform.object;if(!g?.userData.objectId)return;const o=findObject(g.userData.objectId);if(!o)return;if(state.transformMode==='scale'){o.params.w=Math.max(.02,o.params.w*g.scale.x);o.params.h=Math.max(.02,o.params.h*g.scale.y);o.params.d=Math.max(.02,o.params.d*g.scale.z);g.scale.set(1,1,1);rebuild3D();syncObjectInspector(o)}});
function configureGizmo(){transform.setMode(state.transformMode);transformHelper.visible=state.gizmoEnabled&&state.selected?.type==='object';if(!state.gizmoEnabled)transform.detach();else if(state.selected?.type==='object'){const g=renderedObjects.get(state.selected.id);if(g)transform.attach(g)}}
function updateSelectionHelper(g){helperGroup.clear();if(g)helperGroup.add(new THREE.BoxHelper(g,0xffc766))}
function shapeGeometry(points){const s=new THREE.Shape();points.forEach((p,i)=>i?s.lineTo(p.x,p.z):s.moveTo(p.x,p.z));s.closePath();return new THREE.ShapeGeometry(s)}
function rebuild3D(){transform.detach();wallGroup.clear();objectGroup.clear();surfaceGroup.clear();helperGroup.clear();renderedObjects.clear();
  for(const s of state.surfaces){if(s.points.length<3)continue;const geom=shapeGeometry(s.points);const floor=new THREE.Mesh(geom,makeSurfaceMaterial(s.floorMaterial,s.customTexture));floor.rotation.x=-Math.PI/2;floor.position.y=.005;floor.receiveShadow=true;floor.userData.surfaceId=s.id;surfaceGroup.add(floor);if(s.showCeiling){const ceil=new THREE.Mesh(shapeGeometry(s.points),makeSurfaceMaterial(s.ceilingMaterial,s.customTexture));ceil.rotation.x=-Math.PI/2;ceil.position.y=s.ceilingHeight;ceil.userData.surfaceId=s.id;surfaceGroup.add(ceil)}}
  for(const w of state.walls){const dx=w.b.x-w.a.x,dz=w.b.z-w.a.z,len=Math.hypot(dx,dz);if(len<.001)continue;const sel=state.selected?.type==='wall'&&state.selected.id===w.id;const mesh=new THREE.Mesh(new THREE.BoxGeometry(len,w.height,w.thickness),new THREE.MeshStandardMaterial({color:sel?0xf0b85a:(w.kind==='core'?0x89939d:0xc7cbd0),roughness:.78}));mesh.position.set((w.a.x+w.b.x)/2,w.height/2,(w.a.z+w.b.z)/2);mesh.rotation.y=-Math.atan2(dz,dx);mesh.castShadow=mesh.receiveShadow=true;mesh.userData.wallId=w.id;wallGroup.add(mesh)}
  for(const o of state.objects){const def=catalog[o.defIndex];if(!def)continue;const g=createCatalogObject(def,o.params);g.position.set(o.x,o.y,o.z);g.rotation.set(o.rx,o.ry,o.rz);g.userData.objectId=o.id;g.traverse(ch=>ch.userData.objectId=o.id);objectGroup.add(g);renderedObjects.set(o.id,g)}
  if(state.selected?.type==='object'){const g=renderedObjects.get(state.selected.id);if(g){updateSelectionHelper(g);if(state.gizmoEnabled)transform.attach(g)}}configureGizmo();
}
function resize3D(){const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h,false);camera.aspect=Math.max(.01,w/h);camera.updateProjectionMatrix()}function animate(){orbit.update();resize3D();renderer.render(scene,camera);requestAnimationFrame(animate)}animate();

const raycaster=new THREE.Raycaster(),ndc=new THREE.Vector2();renderer.domElement.addEventListener('pointerdown',e=>{if(state.transformSession){confirmTransform();return}if(transform.dragging)return;rememberPointer(e);const r=renderer.domElement.getBoundingClientRect();ndc.x=((e.clientX-r.left)/r.width)*2-1;ndc.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(ndc,camera);let hits=raycaster.intersectObjects(objectGroup.children,true);if(hits.length){let n=hits[0].object;while(n&&!n.userData.objectId)n=n.parent;if(n?.userData.objectId){setTool('select');selectEntity({type:'object',id:n.userData.objectId});return}}hits=raycaster.intersectObjects(surfaceGroup.children,true);if(hits.length&&hits[0].object.userData.surfaceId){setTool('select');selectEntity({type:'surface',id:hits[0].object.userData.surfaceId})}});

// ---------- 2D ----------
function resizeCanvas(){const r=planCanvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2),w=Math.round(r.width*dpr),h=Math.round(r.height*dpr);if(planCanvas.width!==w||planCanvas.height!==h){planCanvas.width=w;planCanvas.height=h}ctx.setTransform(dpr,0,0,dpr,0,0)}
function worldToScreen(p){const r=planCanvas.getBoundingClientRect();return{x:r.width/2+state.pan.x+p.x*state.zoom,y:r.height/2+state.pan.y+p.z*state.zoom}}function screenToWorld(x,y){const r=planCanvas.getBoundingClientRect();return{x:(x-r.width/2-state.pan.x)/state.zoom,z:(y-r.height/2-state.pan.y)/state.zoom}}
function snapGrid(p){const g=state.grid;return{x:Math.round(p.x/g)*g,z:Math.round(p.z/g)*g}}
function snapTarget(origin,raw){let p=snapGrid(raw);if(!origin||!ui.angleSnap.checked)return p;const dx=p.x-origin.x,dz=p.z-origin.z,dist=Math.hypot(dx,dz);if(dist<1e-5)return p;const a=Math.round(Math.atan2(dz,dx)/(Math.PI/4))*(Math.PI/4),d=Math.max(state.grid,Math.round(dist/state.grid)*state.grid);return snapGrid({x:origin.x+Math.cos(a)*d,z:origin.z+Math.sin(a)*d})}
function drawGrid(){const r=planCanvas.getBoundingClientRect();ctx.fillStyle='#0d1116';ctx.fillRect(0,0,r.width,r.height);const minor=state.grid*state.zoom,step=minor<12?minor*Math.ceil(12/minor):minor,o=worldToScreen({x:0,z:0});ctx.strokeStyle='#202832';ctx.lineWidth=1;ctx.beginPath();for(let x=((o.x%step)+step)%step;x<r.width;x+=step){ctx.moveTo(x,0);ctx.lineTo(x,r.height)}for(let y=((o.y%step)+step)%step;y<r.height;y+=step){ctx.moveTo(0,y);ctx.lineTo(r.width,y)}ctx.stroke();ctx.strokeStyle='#3b4653';ctx.beginPath();ctx.moveTo(0,o.y);ctx.lineTo(r.width,o.y);ctx.moveTo(o.x,0);ctx.lineTo(o.x,r.height);ctx.stroke()}
function surfaceColor(s){return s.floorMaterial==='wood'?'#6f543d':s.floorMaterial==='tile'?'#77766e':s.floorMaterial==='checker'?'#5d6065':s.floorMaterial==='carpet'?'#635657':s.floorMaterial==='dark'?'#34383d':'#555b61'}
function drawSurface(s){if(s.points.length<3)return;ctx.beginPath();s.points.forEach((p,i)=>{const q=worldToScreen(p);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.closePath();ctx.globalAlpha=state.selected?.type==='surface'&&state.selected.id===s.id?.38:.22;ctx.fillStyle=state.selected?.type==='surface'&&state.selected.id===s.id?'#d8a852':surfaceColor(s);ctx.fill();ctx.globalAlpha=1;if(state.selected?.type==='surface'&&state.selected.id===s.id){ctx.strokeStyle='#ffd17f';ctx.lineWidth=2;ctx.stroke()}}
function wallLength(w){return Math.hypot(w.b.x-w.a.x,w.b.z-w.a.z)}function drawWall(w){const a=worldToScreen(w.a),b=worldToScreen(w.b),sel=state.selected?.type==='wall'&&state.selected.id===w.id;ctx.lineCap='round';ctx.strokeStyle=sel?'#f0b85a':(w.kind==='core'?'#9aa5b1':'#d5dbe2');ctx.lineWidth=Math.max(3,w.thickness*state.zoom);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();if(sel){ctx.fillStyle='#ffd17f';ctx.font='11px system-ui';ctx.textAlign='center';ctx.fillText(`${wallLength(w).toFixed(2)} m`,(a.x+b.x)/2,(a.y+b.y)/2-10)}}
function drawObject(o){const def=catalog[o.defIndex];if(!def)return;const w=(o.params.w||.5)*state.zoom,d=(o.params.d||.5)*state.zoom,c=worldToScreen({x:o.x,z:o.z}),sel=state.selected?.type==='object'&&state.selected.id===o.id;ctx.save();ctx.translate(c.x,c.y);ctx.rotate(-o.ry);ctx.fillStyle=sel?'#b78947':def.category==='Primitivos'?'#51677a':'#475764';ctx.strokeStyle=sel?'#ffd17f':'#91a0ad';ctx.lineWidth=1.5;ctx.fillRect(-w/2,-d/2,w,d);ctx.strokeRect(-w/2,-d/2,w,d);ctx.restore();if(sel){ctx.fillStyle='#ffd17f';ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillText(def.name,c.x,c.y-d/2-7);if(state.gizmoEnabled)draw2DGizmo(c,w,d,o)}}
function draw2DGizmo(c,w,d,o){ctx.save();ctx.lineWidth=2;if(state.transformMode==='translate'){ctx.strokeStyle='#5fb9ff';ctx.beginPath();ctx.moveTo(c.x-30,c.y);ctx.lineTo(c.x+30,c.y);ctx.moveTo(c.x,c.y-30);ctx.lineTo(c.x,c.y+30);ctx.stroke()}else if(state.transformMode==='rotate'){ctx.strokeStyle='#f0b85a';ctx.beginPath();ctx.arc(c.x,c.y,Math.max(28,Math.hypot(w,d)/2+10),0,Math.PI*2);ctx.stroke()}else{ctx.strokeStyle='#75d68a';ctx.strokeRect(c.x-w/2-5,c.y-d/2-5,w+10,d+10)}ctx.restore()}
function drawHuman2D(){const c=worldToScreen({x:-1.2,z:-1.1});ctx.fillStyle='#68b6ff';ctx.beginPath();ctx.arc(c.x,c.y,.18*state.zoom,0,Math.PI*2);ctx.fill();ctx.fillStyle='#a8d6ff';ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillText('H 1,75 m',c.x,c.y-.28*state.zoom)}
function drawConstructionPreview(){if(!state.hoverWorld)return;if(state.tool==='wall'&&state.drawingPoints.length){const a=worldToScreen(state.drawingPoints.at(-1)),b=worldToScreen(snapTarget(state.drawingPoints.at(-1),state.hoverWorld));ctx.strokeStyle='#70b9ff';ctx.setLineDash([7,5]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([])}else if(state.tool==='rect'&&state.rectStart){const a=worldToScreen(state.rectStart),b=worldToScreen(state.hoverWorld);ctx.strokeStyle='#70b9ff';ctx.setLineDash([7,5]);ctx.strokeRect(Math.min(a.x,b.x),Math.min(a.y,b.y),Math.abs(b.x-a.x),Math.abs(b.y-a.y));ctx.setLineDash([])}}
function renderPlan(){resizeCanvas();drawGrid();state.surfaces.forEach(drawSurface);state.walls.forEach(drawWall);state.objects.forEach(drawObject);drawConstructionPreview();drawHuman2D();requestAnimationFrame(renderPlan)}renderPlan();
function pointerPosition(e){const r=planCanvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function distancePointSegment(p,a,b){const vx=b.x-a.x,vz=b.z-a.z,wx=p.x-a.x,wz=p.z-a.z,l2=vx*vx+vz*vz;if(!l2)return Math.hypot(wx,wz);const t=Math.max(0,Math.min(1,(wx*vx+wz*vz)/l2));return Math.hypot(p.x-(a.x+t*vx),p.z-(a.z+t*vz))}
function pointInPolygon(p,pts){let inside=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){const a=pts[i],b=pts[j];if(((a.z>p.z)!=(b.z>p.z))&&(p.x<(b.x-a.x)*(p.z-a.z)/(b.z-a.z)+a.x))inside=!inside}return inside}
function pick2D(world){for(let i=state.objects.length-1;i>=0;i--){const o=state.objects[i],dx=world.x-o.x,dz=world.z-o.z,c=Math.cos(o.ry),s=Math.sin(o.ry),lx=dx*c-dz*s,lz=dx*s+dz*c;if(Math.abs(lx)<=(o.params.w||.5)/2&&Math.abs(lz)<=(o.params.d||.5)/2)return{type:'object',id:o.id}}let best=null,d=Infinity;for(const w of state.walls){const wd=distancePointSegment(world,w.a,w.b),tol=Math.max(w.thickness/2,7/state.zoom);if(wd<tol&&wd<d){best=w;d=wd}}if(best)return{type:'wall',id:best.id};for(let i=state.surfaces.length-1;i>=0;i--)if(pointInPolygon(world,state.surfaces[i].points))return{type:'surface',id:state.surfaces[i].id};return null}

planCanvas.addEventListener('contextmenu',e=>e.preventDefault());
planCanvas.addEventListener('pointerdown',e=>{rememberPointer(e);const pos=pointerPosition(e);if(state.transformSession){confirmTransform();return}if(e.button===1||e.button===2){state.isPanning=true;state.lastMouse=pos;return}if(e.button!==0)return;const raw=screenToWorld(pos.x,pos.y);
  if(state.tool==='select'){selectEntity(pick2D(raw));return}
  if(state.tool==='rect'){const p=snapGrid(raw);if(!state.rectStart){state.rectStart=p}else{createRectangle(state.rectStart,p);state.rectStart=null;syncScene()}return}
  const origin=state.drawingPoints.at(-1)||null,p=snapTarget(origin,raw);if(!state.drawingPoints.length){state.drawingPoints=[p];return}const first=state.drawingPoints[0],last=state.drawingPoints.at(-1);const closeTol=Math.max(state.grid*.7,10/state.zoom);if(state.drawingPoints.length>=3&&Math.hypot(p.x-first.x,p.z-first.z)<=closeTol){addWall(last.x,last.z,first.x,first.z);createSurface(state.drawingPoints);state.drawingPoints=[];syncScene();return}if(Math.hypot(p.x-last.x,p.z-last.z)>=state.grid/2){addWall(last.x,last.z,p.x,p.z);state.drawingPoints.push(p);syncScene()}
});
planCanvas.addEventListener('pointermove',e=>{rememberPointer(e);const pos=pointerPosition(e);if(state.isPanning&&state.lastMouse){state.pan.x+=pos.x-state.lastMouse.x;state.pan.y+=pos.y-state.lastMouse.y;state.lastMouse=pos;return}state.hoverWorld=screenToWorld(pos.x,pos.y)});planCanvas.addEventListener('pointerup',()=>{state.isPanning=false;state.lastMouse=null});planCanvas.addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(18,Math.min(220,state.zoom*(e.deltaY<0?1.12:.89)))},{passive:false});

// ---------- Blender-like transforms ----------
function rememberPointer(e){state.lastPointer={x:e.clientX,y:e.clientY}}
window.addEventListener('pointermove',e=>{rememberPointer(e);if(state.transformSession)applyTransformFromPointer(e)});
function findObject(id){return state.objects.find(o=>o.id===id)}
function snapshotObject(o){return{x:o.x,y:o.y,z:o.z,rx:o.rx,ry:o.ry,rz:o.rz,w:o.params.w,h:o.params.h,d:o.params.d}}
function restoreSnapshot(o,s){Object.assign(o,{x:s.x,y:s.y,z:s.z,rx:s.rx,ry:s.ry,rz:s.rz});Object.assign(o.params,{w:s.w,h:s.h,d:s.d})}
function beginTransform(mode){if(state.selected?.type!=='object')return;const o=findObject(state.selected.id);if(!o)return;state.transformMode=mode;const modeName=mode==='translate'?'Mover':mode==='rotate'?'Rotar':'Escalar';state.transformSession={mode,axis:null,exclude:null,start:{...state.lastPointer},snapshot:snapshotObject(o),id:o.id};ui.transformHint.hidden=false;ui.transformHint.textContent=`${modeName} · X/Y/Z restringe · Shift+eje excluye · clic confirma · Esc cancela`;configureGizmo()}
function setConstraint(axis,exclude=false){if(!state.transformSession)return;state.transformSession.axis=exclude?null:axis;state.transformSession.exclude=exclude?axis:null;const base=state.transformSession.mode==='translate'?'Mover':state.transformSession.mode==='rotate'?'Rotar':'Escalar';ui.transformHint.textContent=`${base} · ${exclude?'excepto ':''}${axis.toUpperCase()} · clic confirma · Esc cancela`}
function applyTransformFromPointer(e){const s=state.transformSession,o=findObject(s.id);if(!o)return;restoreSnapshot(o,s.snapshot);const dx=e.clientX-s.start.x,dy=e.clientY-s.start.y,m=.01;
  if(s.mode==='translate'){
    if(s.axis==='x')o.x+=dx*m;else if(s.axis==='y')o.y-=dy*m;else if(s.axis==='z')o.z+=dy*m;
    else if(s.exclude==='x'){o.y-=dy*m;o.z+=dx*m}else if(s.exclude==='y'){o.x+=dx*m;o.z+=dy*m}else if(s.exclude==='z'){o.x+=dx*m;o.y-=dy*m}else{o.x+=dx*m;o.z+=dy*m}
  }else if(s.mode==='rotate'){const a=(dx-dy)*.006;if(s.axis==='x')o.rx+=a;else if(s.axis==='y')o.ry+=a;else if(s.axis==='z')o.rz+=a;else if(s.exclude==='x'){o.ry+=a;o.rz+=a}else if(s.exclude==='y'){o.rx+=a;o.rz+=a}else if(s.exclude==='z'){o.rx+=a;o.ry+=a}else o.ry+=a;
  }else{const f=Math.max(.05,1+(dx-dy)*.006);if(s.axis==='x')o.params.w*=f;else if(s.axis==='y')o.params.h*=f;else if(s.axis==='z')o.params.d*=f;else if(s.exclude==='x'){o.params.h*=f;o.params.d*=f}else if(s.exclude==='y'){o.params.w*=f;o.params.d*=f}else if(s.exclude==='z'){o.params.w*=f;o.params.h*=f}else{o.params.w*=f;o.params.h*=f;o.params.d*=f}}
  syncObjectInspector(o);rebuild3D();
}
function confirmTransform(){if(!state.transformSession)return;state.transformSession=null;ui.transformHint.hidden=true;rebuild3D()}
function cancelTransform(){if(!state.transformSession)return;const s=state.transformSession,o=findObject(s.id);if(o){restoreSnapshot(o,s.snapshot);syncObjectInspector(o)}state.transformSession=null;ui.transformHint.hidden=true;rebuild3D()}
ui.gizmoToggle.onclick=()=>{state.gizmoEnabled=!state.gizmoEnabled;ui.gizmoToggle.textContent=`Gizmo: ${state.gizmoEnabled?'ON':'OFF'}`;ui.gizmoToggle.classList.toggle('active',state.gizmoEnabled);configureGizmo()};

// ---------- catalog ----------
function renderLibrary(filter=''){ui.library.innerHTML='';for(const cat of [...new Set(catalog.map(x=>x.category))]){const defs=catalog.map((d,i)=>({...d,i})).filter(d=>d.category===cat&&d.name.toLowerCase().includes(filter.toLowerCase()));if(!defs.length)continue;const title=document.createElement('div');title.className='lib-category';title.textContent=cat;const grid=document.createElement('div');grid.className='lib-grid';for(const d of defs){const b=document.createElement('button');b.className='lib-item'+(cat==='Primitivos'?' primitive':'');b.textContent=d.name;b.onclick=()=>addObject(d.i);grid.appendChild(b)}ui.library.append(title,grid)}}
function addObject(defIndex,x=0,z=0,params={},rotDeg=0){const def=catalog[defIndex];if(!def)return;const o={id:crypto.randomUUID(),defIndex,x,y:0,z,rx:0,ry:THREE.MathUtils.degToRad(rotDeg),rz:0,params:{...def.defaults,...params}};state.objects.push(o);setTool('select');selectEntity({type:'object',id:o.id});syncScene();return o}
ui.search.oninput=()=>renderLibrary(ui.search.value);ui.refresh.onclick=()=>location.reload();renderLibrary();

// ---------- inspectors ----------
function setTool(tool){state.tool=tool;state.drawingPoints=[];state.rectStart=null;ui.wallTool.classList.toggle('active',tool==='wall');ui.rectTool.classList.toggle('active',tool==='rect');ui.selectTool.classList.toggle('active',tool==='select');ui.planStatus.textContent=tool==='wall'?'Pared / polígono':tool==='rect'?'Habitación rectangular':'Seleccionar'}
function hideInspectors(){ui.wallInspector.hidden=ui.objectInspector.hidden=ui.surfaceInspector.hidden=true}
function selectEntity(sel){state.selected=sel;hideInspectors();ui.emptyInspector.hidden=!!sel;if(sel?.type==='wall'){const w=state.walls.find(x=>x.id===sel.id);if(w){ui.wallInspector.hidden=false;ui.wallNumber.textContent=`#${state.walls.indexOf(w)+1}`;ui.wallLength.textContent=wallLength(w).toFixed(2);ui.selectedHeight.value=w.height;ui.selectedThickness.value=w.thickness}}else if(sel?.type==='object'){const o=findObject(sel.id);if(o){ui.objectInspector.hidden=false;ui.objectTitle.textContent=catalog[o.defIndex]?.name||'Objeto';syncObjectInspector(o)}}else if(sel?.type==='surface'){const s=state.surfaces.find(x=>x.id===sel.id);if(s){ui.surfaceInspector.hidden=false;syncSurfaceInspector(s)}}rebuild3D()}
function syncObjectInspector(o){ui.objX.value=o.x.toFixed(2);ui.objY.value=o.y.toFixed(2);ui.objZ.value=o.z.toFixed(2);ui.objRX.value=THREE.MathUtils.radToDeg(o.rx).toFixed(1);ui.objRY.value=THREE.MathUtils.radToDeg(o.ry).toFixed(1);ui.objRZ.value=THREE.MathUtils.radToDeg(o.rz).toFixed(1);ui.objW.value=o.params.w??.5;ui.objH.value=o.params.h??.5;ui.objD.value=o.params.d??.5}
function updateObjFromInspector(){const o=findObject(state.selected?.id);if(!o)return;o.x=Number(ui.objX.value)||0;o.y=Number(ui.objY.value)||0;o.z=Number(ui.objZ.value)||0;o.rx=THREE.MathUtils.degToRad(Number(ui.objRX.value)||0);o.ry=THREE.MathUtils.degToRad(Number(ui.objRY.value)||0);o.rz=THREE.MathUtils.degToRad(Number(ui.objRZ.value)||0);o.params.w=Math.max(.02,Number(ui.objW.value)||.02);o.params.h=Math.max(.02,Number(ui.objH.value)||.02);o.params.d=Math.max(.02,Number(ui.objD.value)||.02);rebuild3D()}
[ui.objX,ui.objY,ui.objZ,ui.objRX,ui.objRY,ui.objRZ,ui.objW,ui.objH,ui.objD].forEach(el=>el.oninput=updateObjFromInspector);
function syncSurfaceInspector(s){ensureCustomOption();ui.floorMaterial.value=s.floorMaterial;ui.ceilingMaterial.value=s.ceilingMaterial;ui.showCeiling.checked=s.showCeiling;ui.ceilingHeight.value=s.ceilingHeight}
function ensureCustomOption(){if(![...ui.floorMaterial.options].some(o=>o.value==='custom')){ui.floorMaterial.add(new Option('Textura propia','custom'));ui.ceilingMaterial.add(new Option('Textura propia','custom'))}}
function updateSurface(){const s=state.surfaces.find(x=>x.id===state.selected?.id);if(!s)return;s.floorMaterial=ui.floorMaterial.value;s.ceilingMaterial=ui.ceilingMaterial.value;s.showCeiling=ui.showCeiling.checked;s.ceilingHeight=Math.max(.2,Number(ui.ceilingHeight.value)||2.6);rebuild3D()}
[ui.floorMaterial,ui.ceilingMaterial,ui.showCeiling,ui.ceilingHeight].forEach(el=>el.oninput=updateSurface);
ui.customTexture.onchange=()=>{const f=ui.customTexture.files?.[0],s=state.surfaces.find(x=>x.id===state.selected?.id);if(!f||!s)return;const r=new FileReader();r.onload=()=>{s.customTexture=r.result;ensureCustomOption();s.floorMaterial='custom';ui.floorMaterial.value='custom';rebuild3D()};r.readAsDataURL(f)};
ui.selectedHeight.oninput=()=>{const w=state.walls.find(x=>x.id===state.selected?.id);if(w){w.height=Math.max(.2,Number(ui.selectedHeight.value)||.2);rebuild3D()}};ui.selectedThickness.oninput=()=>{const w=state.walls.find(x=>x.id===state.selected?.id);if(w){w.thickness=Math.max(.02,Number(ui.selectedThickness.value)||.02);rebuild3D()}};
ui.deleteWall.onclick=()=>{state.walls=state.walls.filter(w=>w.id!==state.selected?.id);selectEntity(null);syncScene()};ui.deleteObject.onclick=()=>{state.objects=state.objects.filter(o=>o.id!==state.selected?.id);selectEntity(null);syncScene()};ui.deleteSurface.onclick=()=>{state.surfaces=state.surfaces.filter(s=>s.id!==state.selected?.id);selectEntity(null);syncScene()};

// ---------- scene helpers / demos ----------
function addWall(x1,z1,x2,z2,height=state.defaultHeight,thickness=state.defaultThickness,kind='wall'){state.walls.push({id:crypto.randomUUID(),a:{x:x1,z:z1},b:{x:x2,z:z2},height,thickness,kind})}
function createSurface(points){state.surfaces.push({id:crypto.randomUUID(),points:points.map(p=>({...p})),floorMaterial:'wood',ceilingMaterial:'white',showCeiling:true,ceilingHeight:state.defaultHeight,customTexture:null})}
function createRectangle(a,b){if(Math.abs(a.x-b.x)<state.grid/2||Math.abs(a.z-b.z)<state.grid/2)return;const pts=[{x:a.x,z:a.z},{x:b.x,z:a.z},{x:b.x,z:b.z},{x:a.x,z:b.z}];for(let i=0;i<4;i++){const p=pts[i],q=pts[(i+1)%4];addWall(p.x,p.z,q.x,q.z)}createSurface(pts)}
function addRect(x1,z1,x2,z2,kind='wall',height=state.defaultHeight,thickness=state.defaultThickness,withSurface=false){const pts=[{x:x1,z:z1},{x:x2,z:z1},{x:x2,z:z2},{x:x1,z:z2}];for(let i=0;i<4;i++){const p=pts[i],q=pts[(i+1)%4];addWall(p.x,p.z,q.x,q.z,height,thickness,kind)}if(withSurface)createSurface(pts)}
function addCatalogByName(name,x,z,params={},rot=0){const i=catalog.findIndex(d=>d.name===name);if(i>=0){const def=catalog[i];state.objects.push({id:crypto.randomUUID(),defIndex:i,x,y:0,z,rx:0,ry:THREE.MathUtils.degToRad(rot),rz:0,params:{...def.defaults,...params}})}}
function clearScene(){state.walls=[];state.objects=[];state.surfaces=[];state.drawingPoints=[];state.rectStart=null;selectEntity(null)}
ui.newPlan.onclick=()=>{clearScene();syncScene()};
ui.demo.onclick=()=>{clearScene();addRect(-3,-2.2,3,2.2,'wall',2.6,.15,true);addCatalogByName('Mesa rectangular',0,0);addCatalogByName('Silla simple',1,0);addCatalogByName('Cajonera',-1.8,1.3);syncScene();state.zoom=70;state.pan={x:0,y:0};camera.position.set(7,6,8);orbit.target.set(0,1,0)};
ui.hotelDemo.onclick=()=>{clearScene();const H=2.7,T=.18,CT=.22;addRect(-12,-4.2,12,4.2,'wall',H,T,true);addWall(-12,-.9,-4.1,-.9,H,T);addWall(-3.2,-.9,3.2,-.9,H,T);addWall(4.1,-.9,12,-.9,H,T);addWall(-12,.9,-4.1,.9,H,T);addWall(-3.2,.9,3.2,.9,H,T);addWall(4.1,.9,12,.9,H,T);for(const x of [-8.1,-4.2,4.2,8.1]){addWall(x,-4.2,x,-.9,H,T);addWall(x,.9,x,4.2,H,T)}addRect(-4.15,-3.05,-3.15,-.95,'core',H,CT);addRect(-4.15,.95,-3.15,3.05,'core',H,CT);addRect(3.15,-3.05,4.15,-.95,'core',H,CT);addRect(3.15,.95,4.15,3.05,'core',H,CT);addWall(-4.15,-2.1,-5.2,-2.1,H,T);addWall(-4.15,2.1,-5.2,2.1,H,T);addWall(4.15,-2.1,5.2,-2.1,H,T);addWall(4.15,2.1,5.2,2.1,H,T);addRect(-3.05,.95,-1.1,4.15,'core',H,CT);addRect(1,.95,3.05,4.15,'core',H,CT);addWall(-1.1,3.1,1,3.1,H,CT);addRect(-2.45,-3.15,.25,-.95,'core',H,CT);addRect(.45,-2.75,1.95,-.95,'core',H,CT);addCatalogByName('Caja',-1.1,-2.05,{w:2.25,h:.08,d:1.7});addCatalogByName('Caja',1.2,-1.85,{w:1.15,h:.08,d:1.35});for(const [x,z,r] of [[-3.65,-2.55,90],[-3.65,2.55,90],[3.65,-2.55,-90],[3.65,2.55,-90]])addCatalogByName('Inodoro',x,z,{w:.55,h:.75,d:.75},r);syncScene();setTool('select');state.zoom=31;state.pan={x:0,y:0};orbit.target.set(0,1.1,0);camera.position.set(15,13,16)};

function syncScene(){ui.wallCount.textContent=state.walls.length;ui.objectCount.textContent=state.objects.length+1;ui.surfaceCount.textContent=state.surfaces.length;rebuild3D()}
ui.wallTool.onclick=()=>setTool('wall');ui.rectTool.onclick=()=>setTool('rect');ui.selectTool.onclick=()=>setTool('select');ui.defaultHeight.oninput=()=>state.defaultHeight=Number(ui.defaultHeight.value)||2.6;ui.wallThickness.oninput=()=>state.defaultThickness=Number(ui.wallThickness.value)||.15;ui.gridSize.onchange=()=>state.grid=Number(ui.gridSize.value);

document.addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;const k=e.key.toLowerCase();if(state.transformSession){if(k==='escape'){cancelTransform();return}if(['x','y','z'].includes(k)){setConstraint(k,e.shiftKey);return}if(k==='enter'){confirmTransform();return}}
  if(k==='g'){beginTransform('translate');return}if(k==='r'){beginTransform('rotate');return}if(k==='s'){beginTransform('scale');return}if(k==='escape'){state.drawingPoints=[];state.rectStart=null;return}if(k==='w')setTool('wall');if(k==='b')setTool('rect');if(k==='v')setTool('select');if((k==='delete'||k==='backspace')&&state.selected){if(state.selected.type==='wall')ui.deleteWall.click();else if(state.selected.type==='object')ui.deleteObject.click();else ui.deleteSurface.click()}});
window.addEventListener('resize',()=>{resizeCanvas();resize3D()});state.grid=Number(ui.gridSize.value);syncScene();